# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9772a0d49c960ecf00fb6d164d1843f6a520ef3d8dd3033a3021abecf2382f71cb57d7b1b2f1f3205649bcdc754ffe92c68aac2eea2c2372404a523f6d0e2413

test:
  secret_key_base: 381beeecc0ceabf4481253361616097746e35d2a9d697e33d24dee961e437162d6c18119c141878e717d575c02dd768d8cdca84770c2492d6453acc8c62e0dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
